-- Phase 2: personal web/profile system
CREATE TABLE IF NOT EXISTS proton_themes (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id CHAR(26) NOT NULL, owner_account_id BIGINT UNSIGNED NULL, name VARCHAR(120) NOT NULL, theme_json JSON NOT NULL, moderation_status ENUM('draft','pending','approved','rejected','disabled') NOT NULL DEFAULT 'draft', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY uq_proton_theme_public(public_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS proton_profile_modules (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, profile_id BIGINT UNSIGNED NOT NULL, module_key VARCHAR(80) NOT NULL, module_type VARCHAR(50) NOT NULL, column_key VARCHAR(40) NOT NULL, position_index INT UNSIGNED NOT NULL, title VARCHAR(120) NULL, configuration_json JSON NOT NULL, is_enabled BOOLEAN NOT NULL DEFAULT TRUE, PRIMARY KEY(id), UNIQUE KEY uq_proton_module(profile_id,module_key), KEY idx_proton_module_position(profile_id,column_key,position_index)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS proton_guestbook_entries (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id CHAR(26) NOT NULL, profile_id BIGINT UNSIGNED NOT NULL, author_account_id BIGINT UNSIGNED NOT NULL, body TEXT NOT NULL, moderation_status ENUM('visible','pending','hidden','removed') NOT NULL DEFAULT 'visible', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY uq_proton_guestbook_public(public_id), KEY idx_proton_guestbook_profile(profile_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS proton_follows (follower_account_id BIGINT UNSIGNED NOT NULL, followed_account_id BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(follower_account_id,followed_account_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Phase 3: persisted chat and moderation records; realtime transport remains replaceable.
CREATE TABLE IF NOT EXISTS proton_chat_rooms (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id CHAR(26) NOT NULL, room_type ENUM('public','group','event','business','creator','private') NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, visibility ENUM('public','listed','private') NOT NULL DEFAULT 'public', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY uq_proton_room_public(public_id), UNIQUE KEY uq_proton_room_slug(slug)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS proton_chat_messages (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id CHAR(26) NOT NULL, room_id BIGINT UNSIGNED NOT NULL, account_id BIGINT UNSIGNED NOT NULL, body TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at DATETIME NULL, PRIMARY KEY(id), UNIQUE KEY uq_proton_message_public(public_id), KEY idx_proton_room_messages(room_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Phase 4: approved app distribution and generalized pages.
CREATE TABLE IF NOT EXISTS proton_apps (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id CHAR(26) NOT NULL, app_key VARCHAR(100) NOT NULL, developer_account_id BIGINT UNSIGNED NULL, name VARCHAR(120) NOT NULL, description TEXT NULL, category VARCHAR(60) NOT NULL, route_type ENUM('cityos-local','fivem-resource','proton-route','approved-web') NOT NULL, route TEXT NOT NULL, manifest_json JSON NOT NULL, status ENUM('draft','review','published','suspended','retired') NOT NULL DEFAULT 'draft', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY uq_proton_app_public(public_id), UNIQUE KEY uq_proton_app_key(app_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS proton_app_installations (account_id BIGINT UNSIGNED NOT NULL, app_id BIGINT UNSIGNED NOT NULL, installed_version VARCHAR(40) NULL, is_favorite BOOLEAN NOT NULL DEFAULT FALSE, settings_json JSON NULL, installed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(account_id,app_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS proton_pages (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id CHAR(26) NOT NULL, page_type ENUM('business','group','government','news','creator','organization') NOT NULL, external_reference VARCHAR(190) NULL, slug VARCHAR(100) NOT NULL, name VARCHAR(140) NOT NULL, description TEXT NULL, owner_account_id BIGINT UNSIGNED NULL, verification_status ENUM('none','verified','official') NOT NULL DEFAULT 'none', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY uq_proton_page_public(public_id), UNIQUE KEY uq_proton_page_slug(slug)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Phase 5: media, live records, creator accounting, and reports.
CREATE TABLE IF NOT EXISTS proton_media (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id CHAR(26) NOT NULL, owner_account_id BIGINT UNSIGNED NOT NULL, media_type ENUM('image','audio','video','document') NOT NULL, storage_provider VARCHAR(50) NOT NULL, storage_key VARCHAR(500) NOT NULL, mime_type VARCHAR(120) NOT NULL, size_bytes BIGINT UNSIGNED NOT NULL, moderation_status ENUM('processing','approved','rejected','quarantined') NOT NULL DEFAULT 'processing', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY uq_proton_media_public(public_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS proton_streams (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id CHAR(26) NOT NULL, creator_account_id BIGINT UNSIGNED NOT NULL, title VARCHAR(180) NOT NULL, category VARCHAR(80) NOT NULL, status ENUM('scheduled','live','ended','cancelled') NOT NULL DEFAULT 'scheduled', provider VARCHAR(60) NULL, playback_url TEXT NULL, scheduled_at DATETIME NULL, started_at DATETIME NULL, ended_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY uq_proton_stream_public(public_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS proton_creator_ledger (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id CHAR(26) NOT NULL, creator_account_id BIGINT UNSIGNED NOT NULL, entry_type ENUM('sale','tip','refund','chargeback','processing_fee','platform_fee','adjustment','payout') NOT NULL, currency CHAR(3) NOT NULL, gross_amount_minor BIGINT NOT NULL, processing_fee_minor BIGINT NOT NULL DEFAULT 0, platform_fee_minor BIGINT NOT NULL DEFAULT 0, net_amount_minor BIGINT NOT NULL, settlement_status ENUM('pending','available','paid','reversed') NOT NULL DEFAULT 'pending', external_transaction_id VARCHAR(190) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY uq_proton_ledger_public(public_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS proton_reports (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id CHAR(26) NOT NULL, reporter_account_id BIGINT UNSIGNED NOT NULL, target_type VARCHAR(40) NOT NULL, target_id BIGINT UNSIGNED NOT NULL, reason VARCHAR(80) NOT NULL, details TEXT NULL, status ENUM('open','reviewing','resolved','dismissed') NOT NULL DEFAULT 'open', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY uq_proton_report_public(public_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Rollback: drop these tables in reverse dependency order only after disabling phases 2-5.
-- DROP TABLE proton_reports, proton_creator_ledger, proton_streams, proton_media, proton_pages, proton_app_installations, proton_apps, proton_chat_messages, proton_chat_rooms, proton_guestbook_entries, proton_profile_modules, proton_themes;
