import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
await rm(resolve(root, 'dist'), { recursive: true, force: true });
await mkdir(resolve(root, 'dist'), { recursive: true });
await cp(resolve(root, 'public'), resolve(root, 'dist'), { recursive: true });
const indexPath = resolve(root, 'dist', 'index.html');
const index = await readFile(indexPath, 'utf8');
await writeFile(indexPath, index.replace('</body>', '<script src="auth-gate.js"></script></body>'));
console.log('ProtonSpace static site built in apps/web/dist');
