import { createServer, IncomingMessage, ServerResponse } from 'node:http';
import { createHmac, randomBytes, randomUUID } from 'node:crypto';
import { createReadStream, createWriteStream } from 'node:fs';
import { mkdir, stat, unlink, writeFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
import mysql from 'mysql2/promise';
import Busboy from 'busboy';

const port = Number(process.env.PORT ?? 4080);
const origin = process.env.PROTONSPACE_WEB_ORIGIN ?? 'http://localhost:5173';
const cityosSecret = process.env.CITYOS_PROTON_TICKET_SECRET ?? '';
const discordClientId = process.env.DISCORD_CLIENT_ID ?? '1528626770557931742';
const discordClientSecret = process.env.DISCORD_CLIENT_SECRET ?? '';
const publicSite = process.env.PROTONSPACE_WEB_URL ?? 'https://nicojones23.github.io/protonspace/';
const oauthStateSecret = process.env.DISCORD_OAUTH_STATE_SECRET ?? (discordClientSecret || cityosSecret);
const mediaRoot = process.env.PROTONSPACE_MEDIA_ROOT ?? join(process.cwd(),'uploads');
const mediaBaseUrl = (process.env.PROTONSPACE_MEDIA_BASE_URL ?? 'https://api.mhprotonspace.org/media').replace(/\/$/,'');
const pool = mysql.createPool(process.env.DATABASE_URL ?? 'mysql://cityos:CHANGE_ME@127.0.0.1/cityos_fivem');

type Session = { accountId: number; characterId?: string; activeIdentityId: number; identityLocked: number; expiresAt: number };
const tickets = new Map<string, { accountId: number; identityId: number; citizenId: string; expiresAt: number; used: boolean }>();
function makeOAuthState() { const payload=Buffer.from(`${Date.now()}.${randomUUID()}`).toString('base64url'); const sig=createHmac('sha256',oauthStateSecret).update(payload).digest('base64url'); return `${payload}.${sig}`; }
function validOAuthState(state:string) { const [payload,sig]=state.split('.'); if(!payload||!sig||!oauthStateSecret)return false; const expected=createHmac('sha256',oauthStateSecret).update(payload).digest('base64url'); if(sig!==expected)return false; const issued=Number(Buffer.from(payload,'base64url').toString().split('.')[0]); return Number.isFinite(issued)&&Date.now()-issued<600000; }

function json(res: ServerResponse, status: number, body: unknown) { res.writeHead(status, {'content-type':'application/json; charset=utf-8','access-control-allow-origin':origin,'access-control-allow-credentials':'true','access-control-allow-methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS','access-control-allow-headers':'Content-Type'}); res.end(JSON.stringify(body)); }
async function body(req: IncomingMessage) { let raw=''; for await (const chunk of req) raw += chunk; return raw ? JSON.parse(raw) : {}; }
function cookie(req: IncomingMessage, name: string) { return (req.headers.cookie ?? '').split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1); }
async function session(req: IncomingMessage) { const key=cookie(req,'proton_session'); if(!key)return null; const [rows]=await pool.query('SELECT account_id AS accountId,character_id AS characterId,active_identity_id AS activeIdentityId,identity_locked AS identityLocked,UNIX_TIMESTAMP(expires_at)*1000 AS expiresAt FROM proton_sessions WHERE id=? AND expires_at>NOW() LIMIT 1',[key]); return (rows as Session[])[0]??null; }
async function personalIdentity(accountId:number) { const [rows]=await pool.query(`SELECT i.id FROM proton_identities i JOIN proton_identity_members im ON im.identity_id=i.id WHERE im.account_id=? AND i.identity_type='personal' AND i.identity_status='active' LIMIT 1`,[accountId]); let id=Number((rows as any[])[0]?.id); if(id)return id; const [accountRows]=await pool.query('SELECT username,display_name AS displayName FROM proton_accounts WHERE id=?',[accountId]); const account=(accountRows as any[])[0]; const [result]=await pool.query('INSERT INTO proton_identities (public_id,identity_type,username,display_name) VALUES (?,"personal",?,?)',[publicId(),`p_${account.username}`.slice(0,80),account.displayName]); id=Number((result as any).insertId); await pool.query('INSERT INTO proton_identity_members (identity_id,account_id,member_role) VALUES (?, ?, "owner")',[id,accountId]); return id; }
async function createSession(accountId:number,characterId?:string,activeIdentityId?:number,locked=false) { const id=randomUUID(),identityId=activeIdentityId||await personalIdentity(accountId); await pool.query('INSERT INTO proton_sessions (id,account_id,character_id,active_identity_id,identity_locked,expires_at) VALUES (?,?,?,?,?,DATE_ADD(NOW(),INTERVAL 30 DAY))',[id,accountId,characterId??null,identityId,locked]); return id; }
async function identitiesFor(accountId:number) { const [rows]=await pool.query(`SELECT i.public_id AS publicId,i.identity_type AS type,i.username,i.display_name AS displayName,i.avatar_url AS avatarUrl,im.member_role AS role,im.can_post AS canPost,im.can_edit_profile AS canEditProfile FROM proton_identity_members im JOIN proton_identities i ON i.id=im.identity_id WHERE im.account_id=? AND i.identity_status='active' ORDER BY FIELD(i.identity_type,'personal','character','page'),i.display_name`,[accountId]); return rows as any[]; }
async function activeIdentity(current:Session) { const [rows]=await pool.query(`SELECT i.id,i.public_id AS publicId,i.identity_type AS type,i.username,i.display_name AS displayName,i.avatar_url AS avatarUrl,im.member_role AS role,im.can_post AS canPost,im.can_edit_profile AS canEditProfile FROM proton_identities i JOIN proton_identity_members im ON im.identity_id=i.id AND im.account_id=? WHERE i.id=? AND i.identity_status='active' LIMIT 1`,[current.accountId,current.activeIdentityId]); return (rows as any[])[0]??null; }
function publicId() { return randomBytes(16).toString('hex').slice(0,26); }
const mediaTypes:Record<string,string>={'image/jpeg':'.jpg','image/png':'.png','image/gif':'.gif','image/webp':'.webp'};
async function upload(req:IncomingMessage) { await mkdir(mediaRoot,{recursive:true}); return new Promise<{filename:string;mimeType:string;size:number}>((resolve,reject)=>{const bb=Busboy({headers:req.headers,limits:{files:1,fileSize:8*1024*1024,fields:4}});let saved:any=null,failed=false;bb.on('file',(_name,file,info)=>{const extension=mediaTypes[info.mimeType];if(!extension){failed=true;file.resume();return}const filename=`${randomUUID()}${extension}`,path=join(mediaRoot,filename),out=createWriteStream(path,{flags:'wx'});let size=0;file.on('data',chunk=>size+=chunk.length);file.on('limit',()=>{failed=true;out.destroy();unlink(path).catch(()=>{})});file.pipe(out);saved={filename,mimeType:info.mimeType,size,path};});bb.on('error',reject);bb.on('finish',()=>saved&&!failed?resolve(saved):reject(new Error('invalid_media_upload')));req.pipe(bb);}); }

async function route(req: IncomingMessage, res: ServerResponse) {
  if (req.method === 'OPTIONS') return json(res,204,{});
  const url = new URL(req.url ?? '/', `http://${req.headers.host ?? 'localhost'}`);
  if (req.method === 'GET' && url.pathname === '/health') return json(res,200,{ok:true,service:'protonspace-api'});
  const mediaFile=url.pathname.match(/^\/media\/([a-f0-9-]+\.(?:jpg|png|gif|webp))$/i);
  if(req.method==='GET'&&mediaFile){try{const path=join(mediaRoot,mediaFile[1]),details=await stat(path),type:Record<string,string>={'.jpg':'image/jpeg','.png':'image/png','.gif':'image/gif','.webp':'image/webp'};res.writeHead(200,{'content-type':type[extname(path).toLowerCase()]||'application/octet-stream','content-length':details.size,'cache-control':'public,max-age=31536000,immutable','x-content-type-options':'nosniff'});return createReadStream(path).pipe(res)}catch{return json(res,404,{error:'media_not_found'})}}
  if (req.method === 'GET' && (url.pathname === '/api/auth/session' || url.pathname === '/api/auth/me')) { const current=await session(req); if(!current)return json(res,200,{authenticated:false}); const identity=await activeIdentity(current); return json(res,200,{authenticated:true,identity,identities:current.identityLocked?(identity?[identity]:[]):await identitiesFor(current.accountId),identityLocked:Boolean(current.identityLocked),surface:current.identityLocked?'game':'web'}); }
  if (req.method === 'POST' && url.pathname === '/api/auth/logout') { const key=cookie(req,'proton_session'); if(key)await pool.query('DELETE FROM proton_sessions WHERE id=?',[key]); res.setHeader('set-cookie','proton_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0'); return json(res,200,{ok:true}); }
  if (req.method === 'GET' && url.pathname === '/api/auth/discord') {
    if (!discordClientSecret) return json(res,503,{error:'discord_login_not_configured'});
    const state=makeOAuthState(); const redirect='https://api.mhprotonspace.org/api/auth/discord/callback';
    res.writeHead(302,{location:`https://discord.com/oauth2/authorize?client_id=${encodeURIComponent(discordClientId)}&response_type=code&redirect_uri=${encodeURIComponent(redirect)}&scope=identify&state=${encodeURIComponent(state)}`}); return res.end();
  }
  if (req.method === 'GET' && url.pathname === '/api/auth/discord/callback') {
    const callbackId=randomUUID().slice(0,8); console.log(`[discord:${callbackId}] callback_received`);
    const code=url.searchParams.get('code')||'', state=url.searchParams.get('state')||'';
    if (!code || !validOAuthState(state)) { console.warn(`[discord:${callbackId}] invalid_state`); return json(res,400,{error:'invalid_oauth_state',callbackId}); }
    try {
      const redirect='https://api.mhprotonspace.org/api/auth/discord/callback'; console.log(`[discord:${callbackId}] token_exchange_start`);
      const tokenRes=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:discordClientId,client_secret:discordClientSecret,grant_type:'authorization_code',code,redirect_uri:redirect}),signal:AbortSignal.timeout(10000)});
      if(!tokenRes.ok){console.warn(`[discord:${callbackId}] token_exchange_failed status=${tokenRes.status}`);return json(res,502,{error:'discord_token_exchange_failed',callbackId});}
      const token=await tokenRes.json() as any; console.log(`[discord:${callbackId}] identity_start`);
      const userRes=await fetch('https://discord.com/api/v10/users/@me',{headers:{authorization:`Bearer ${token.access_token}`},signal:AbortSignal.timeout(10000)});
      if(!userRes.ok){console.warn(`[discord:${callbackId}] identity_failed status=${userRes.status}`);return json(res,502,{error:'discord_identity_failed',callbackId});}
      const user=await userRes.json() as any; console.log(`[discord:${callbackId}] database_start`);
      const username=('discord_'+String(user.id)).slice(0,40), displayName=String(user.global_name||user.username||'Discord user').slice(0,80), accountPublicId=publicId(); await pool.query('INSERT INTO proton_accounts (public_id,username,display_name,discord_id,last_login_at) VALUES (?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE display_name=VALUES(display_name),last_login_at=NOW()',[accountPublicId,username,displayName,String(user.id)]); const [accounts]=await pool.query('SELECT id FROM proton_accounts WHERE discord_id=? AND account_status="active" LIMIT 1',[String(user.id)]); const accountId=Number((accounts as any[])[0]?.id); if(!accountId)return json(res,500,{error:'account_link_failed',callbackId});
      const sessionId=await createSession(accountId); console.log(`[discord:${callbackId}] complete`); res.setHeader('set-cookie',`proton_session=${sessionId}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=2592000`); res.writeHead(302,{location:publicSite}); return res.end();
    } catch(error:any) { console.error(`[discord:${callbackId}] exception ${error?.name||'Error'} ${error?.code||''}`); return json(res,502,{error:'discord_callback_failed',callbackId}); }
  }
  if (req.method === 'POST' && url.pathname === '/api/auth/ticket/exchange') {
    const input=await body(req); const ticket=tickets.get(String(input.ticket ?? ''));
    if (!ticket || ticket.used || ticket.expiresAt<Date.now()) return json(res,401,{error:'invalid_ticket'});
    ticket.used=true; const sessionId=await createSession(ticket.accountId,ticket.citizenId,ticket.identityId,true);
    res.setHeader('set-cookie',`proton_session=${sessionId}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=2592000`); return json(res,200,{ok:true,surface:'web'});
  }
  if (req.method === 'POST' && url.pathname === '/internal/cityos/tickets') {
    if (!cityosSecret || req.headers['x-cityos-ticket-secret'] !== cityosSecret) return json(res,403,{error:'forbidden'});
    const input=await body(req); const citizenId=typeof input.citizenId==='string'?input.citizenId.trim():''; const name=typeof input.characterName==='string'?input.characterName.trim():''; const discordId=typeof input.discordId==='string'?input.discordId.trim():''; const serverKey=String(input.serverKey||'most_hated_rp').slice(0,80);
    if(!citizenId||!name)return json(res,400,{error:'character_required'});
    const [linked]=await pool.query('SELECT account_id AS accountId,identity_id AS identityId FROM proton_character_links WHERE citizenid=? LIMIT 1',[citizenId]); const existing=(linked as any[])[0];
    const linkedAccountId=Number(existing?.accountId); let accountId=linkedAccountId; if(discordId){const [accounts]=await pool.query('SELECT id FROM proton_accounts WHERE discord_id=? AND account_status="active" LIMIT 1',[discordId]); const discordAccount=Number((accounts as any[])[0]?.id); if(discordAccount){if(accountId&&accountId!==discordAccount){const [owners]=await pool.query('SELECT discord_id AS discordId FROM proton_accounts WHERE id=?',[accountId]);if((owners as any[])[0]?.discordId)return json(res,409,{error:'character_transfer_required'});}accountId=discordAccount;}}
    if(!accountId){const username=('discord_'+(discordId||citizenId)).toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,40);await pool.query('INSERT INTO proton_accounts (public_id,username,display_name,discord_id) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE display_name=VALUES(display_name)',[publicId(),username,name,discordId||null]);const [accounts]=await pool.query(discordId?'SELECT id FROM proton_accounts WHERE discord_id=? LIMIT 1':'SELECT id FROM proton_accounts WHERE username=? LIMIT 1',[discordId||username]);accountId=Number((accounts as any[])[0]?.id);}
    if(!accountId)return json(res,500,{error:'account_link_failed'});
    let identityId=Number(existing?.identityId); if(!identityId){const username=('c_'+citizenId).toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,80);await pool.query('INSERT INTO proton_identities (public_id,identity_type,username,display_name) VALUES (?,"character",?,?) ON DUPLICATE KEY UPDATE display_name=VALUES(display_name)',[publicId(),username,name]);const [identities]=await pool.query('SELECT id FROM proton_identities WHERE username=? LIMIT 1',[username]);identityId=Number((identities as any[])[0]?.id);}
    if(!identityId)return json(res,500,{error:'identity_link_failed'}); await pool.query('INSERT IGNORE INTO proton_identity_members (identity_id,account_id,member_role) VALUES (?, ?, "owner")',[identityId,accountId]); if(linkedAccountId&&linkedAccountId!==accountId){await pool.query('DELETE im FROM proton_identity_members im JOIN proton_accounts a ON a.id=im.account_id WHERE im.identity_id=? AND im.account_id=? AND a.discord_id IS NULL',[identityId,linkedAccountId]);}
    await pool.query('INSERT INTO proton_character_links (account_id,identity_id,citizenid,character_name,server_key,is_primary,is_verified,last_seen_in_city_at) VALUES (?,?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE account_id=VALUES(account_id),identity_id=VALUES(identity_id),character_name=VALUES(character_name),server_key=VALUES(server_key),is_verified=VALUES(is_verified),last_seen_in_city_at=NOW()',[accountId,identityId,citizenId,name,serverKey,true,true]);
    const ticket=randomUUID(); tickets.set(ticket,{accountId,identityId,citizenId,expiresAt:Date.now()+45000,used:false}); return json(res,200,{ticket,expiresIn:45,exchangePath:'/api/auth/ticket/exchange'});
  }
  if (req.method === 'GET' && url.pathname === '/api/feed') { const [raw]=await pool.query(`SELECT p.id AS internalId,p.public_id AS publicId,p.body,p.published_at AS publishedAt,i.public_id AS identityPublicId,i.identity_type AS identityType,i.username,i.display_name AS displayName,i.avatar_url AS avatarUrl FROM proton_posts p JOIN proton_identities i ON i.id=p.identity_id WHERE p.visibility='public' AND p.moderation_status='visible' AND p.deleted_at IS NULL AND i.identity_status='active' ORDER BY p.published_at DESC LIMIT 100`); const posts=raw as any[]; if(posts.length){const [mediaRows]=await pool.query(`SELECT pm.post_id AS postId,m.public_id AS publicId,m.mime_type AS mimeType,m.storage_provider AS provider,m.storage_key AS storageKey,m.source_url AS sourceUrl FROM proton_post_media pm JOIN proton_media m ON m.id=pm.media_id WHERE pm.post_id IN (?) AND m.moderation_status='approved' ORDER BY pm.position_index`,[posts.map(p=>p.internalId)]);for(const post of posts){post.media=(mediaRows as any[]).filter(m=>Number(m.postId)===Number(post.internalId)).map(m=>({publicId:m.publicId,mimeType:m.mimeType,url:m.provider==='local'?`${mediaBaseUrl}/${m.storageKey}`:m.sourceUrl}));delete post.internalId}} return json(res,200,{posts}); }
  if (req.method === 'GET' && url.pathname === '/api/directory') { const [rows]=await pool.query(`SELECT public_id AS publicId,identity_type AS type,username,display_name AS displayName,avatar_url AS avatarUrl,created_at AS joinedAt FROM proton_identities WHERE identity_status='active' AND visibility='public' ORDER BY created_at DESC LIMIT 50`); return json(res,200,{people:rows}); }
  const current=await session(req); if (!current) return json(res,401,{error:'authentication_required'});
  if (req.method === 'GET' && url.pathname === '/api/me') { const [rows]=await pool.query(`SELECT i.public_id AS publicId,i.identity_type AS type,i.username,i.display_name AS displayName,p.slug,p.headline,p.bio,p.mood,p.location_label AS location,p.visibility,p.avatar_url AS avatarUrl,p.cover_url AS coverUrl,p.interests,p.theme_json AS theme FROM proton_identities i JOIN proton_identity_members im ON im.identity_id=i.id AND im.account_id=? LEFT JOIN proton_profiles p ON p.identity_id=i.id WHERE i.id=? LIMIT 1`,[current.accountId,current.activeIdentityId]); return json(res,200,{identity:(rows as any[])[0]??null,identityLocked:Boolean(current.identityLocked)}); }
  if (req.method === 'POST' && url.pathname === '/api/auth/identity') { if(current.identityLocked)return json(res,403,{error:'identity_locked_to_game_character'}); const input=await body(req); const [rows]=await pool.query(`SELECT i.id FROM proton_identities i JOIN proton_identity_members im ON im.identity_id=i.id WHERE i.public_id=? AND im.account_id=? AND i.identity_status='active' LIMIT 1`,[String(input.identityPublicId||''),current.accountId]); const identityId=Number((rows as any[])[0]?.id); if(!identityId)return json(res,404,{error:'identity_not_available'}); const key=cookie(req,'proton_session'); await pool.query('UPDATE proton_sessions SET active_identity_id=? WHERE id=?',[identityId,key]); return json(res,200,{ok:true}); }
  if (req.method === 'POST' && url.pathname === '/api/uploads') { try{const file=await upload(req),id=publicId();await pool.query('INSERT INTO proton_media (public_id,owner_account_id,media_type,storage_provider,storage_key,mime_type,size_bytes,moderation_status) VALUES (?, ?, "image", "local", ?, ?, ?, "approved")',[id,current.accountId,file.filename,file.mimeType,file.size]);return json(res,201,{publicId:id,url:`${mediaBaseUrl}/${file.filename}`,mimeType:file.mimeType})}catch{return json(res,400,{error:'invalid_media_upload',allowed:['image/jpeg','image/png','image/gif','image/webp'],maxBytes:8388608})} }
  if (req.method === 'POST' && url.pathname === '/api/uploads/import') { const input=await body(req);try{const external=new URL(String(input.url??'')),allowedHosts=['media.giphy.com','i.giphy.com','media.tenor.com','c.tenor.com'];if(external.protocol!=='https:'||!allowedHosts.some(host=>external.hostname===host||external.hostname.endsWith('.'+host)))throw new Error();const remote=await fetch(external,{redirect:'follow',signal:AbortSignal.timeout(10000)});if(!remote.ok)throw new Error();const mimeType=(remote.headers.get('content-type')||'').split(';')[0],extension=mediaTypes[mimeType];if(!extension)throw new Error();const bytes=Buffer.from(await remote.arrayBuffer());if(!bytes.length||bytes.length>8*1024*1024)throw new Error();await mkdir(mediaRoot,{recursive:true});const filename=`${randomUUID()}${extension}`;await writeFile(join(mediaRoot,filename),bytes,{flag:'wx'});const id=publicId();await pool.query('INSERT INTO proton_media (public_id,owner_account_id,media_type,storage_provider,storage_key,mime_type,size_bytes,moderation_status,source_url) VALUES (?, ?, "image", "local", ?, ?, ?, "approved", ?)',[id,current.accountId,filename,mimeType,bytes.length,external.toString()]);return json(res,201,{publicId:id,url:`${mediaBaseUrl}/${filename}`,mimeType})}catch{return json(res,400,{error:'invalid_gif_url',providers:['GIPHY','Tenor'],maxBytes:8388608})} }
  if (req.method === 'POST' && url.pathname === '/api/posts') { const input=await body(req); const text=typeof input.body==='string'?input.body.trim():''; const mediaIds=Array.isArray(input.mediaPublicIds)?input.mediaPublicIds.slice(0,4):[]; if((!text&&!mediaIds.length)||text.length>2000)return json(res,400,{error:'invalid_body'}); const identity=await activeIdentity(current); if(!identity||!identity.canPost)return json(res,403,{error:'identity_cannot_post'}); const id=publicId(); const [result]=await pool.query('INSERT INTO proton_posts (public_id,author_type,author_id,account_id,citizenid,identity_id,created_by_account_id,body) VALUES (?,?,?,?,?,?,?,?)',[id,identity.type,identity.id,current.accountId,current.characterId??null,identity.id,current.accountId,text]);if(mediaIds.length){const [media]=await pool.query('SELECT id FROM proton_media WHERE public_id IN (?) AND owner_account_id=? AND moderation_status="approved"',[mediaIds,current.accountId]);let position=0;for(const item of media as any[])await pool.query('INSERT INTO proton_post_media (post_id,media_id,position_index) VALUES (?,?,?)',[(result as any).insertId,item.id,position++])} return json(res,201,{publicId:id,identity:{publicId:identity.publicId,type:identity.type,displayName:identity.displayName}}); }
  const commentMatch=url.pathname.match(/^\/api\/posts\/([^/]+)\/comments$/);
  if (req.method === 'GET' && commentMatch) { const [rows]=await pool.query('SELECT c.public_id AS publicId,c.body,c.created_at AS createdAt,a.username,a.display_name AS displayName FROM proton_comments c JOIN proton_posts p ON p.id=c.post_id JOIN proton_accounts a ON a.id=c.account_id WHERE p.public_id=? AND c.moderation_status="visible" ORDER BY c.created_at ASC LIMIT 100',[commentMatch[1]]); return json(res,200,{comments:rows}); }
  if (req.method === 'POST' && commentMatch) { const input=await body(req); const text=typeof input.body==='string'?input.body.trim():''; if(!text||text.length>2000)return json(res,400,{error:'invalid_body'}); const [posts]=await pool.query('SELECT id,account_id FROM proton_posts WHERE public_id=? AND moderation_status="visible" AND deleted_at IS NULL',[commentMatch[1]]); const post=(posts as any[])[0]; if(!post)return json(res,404,{error:'post_not_found'}); const id=publicId(); await pool.query('INSERT INTO proton_comments (public_id,post_id,account_id,body) VALUES (?,?,?,?)',[id,post.id,current.accountId,text]); if(Number(post.account_id)!==current.accountId) await pool.query('INSERT INTO proton_notifications (public_id,account_id,notification_type,title,message,route) VALUES (?,?,?,?,?,?)',[publicId(),post.account_id,'comment','New comment','Someone commented on your post','/p/'+commentMatch[1]]); return json(res,201,{publicId:id}); }
  const reactionMatch=url.pathname.match(/^\/api\/posts\/([^/]+)\/reaction$/);
  if (req.method === 'PUT' && reactionMatch) { const input=await body(req); const reaction=['like','love','fire','laugh','wow','clap'].includes(input.reaction)?input.reaction:null; if(!reaction)return json(res,400,{error:'invalid_reaction'}); const [posts]=await pool.query('SELECT id FROM proton_posts WHERE public_id=? AND deleted_at IS NULL',[reactionMatch[1]]); const post=(posts as any[])[0]; if(!post)return json(res,404,{error:'post_not_found'}); await pool.query('INSERT INTO proton_reactions (target_type,target_id,account_id,reaction) VALUES ("post",?,?,?) ON DUPLICATE KEY UPDATE reaction=VALUES(reaction),created_at=CURRENT_TIMESTAMP',[post.id,current.accountId,reaction]); return json(res,200,{ok:true,reaction}); }
  const followMatch=url.pathname.match(/^\/api\/follows\/([^/]+)$/);
  if ((req.method === 'POST' || req.method === 'DELETE') && followMatch) { const [targets]=await pool.query(`SELECT i.id FROM proton_identities i WHERE i.public_id=? AND i.identity_status='active'`,[followMatch[1]]); const followed=Number((targets as any[])[0]?.id); if(!followed)return json(res,404,{error:'identity_not_found'}); if(followed===current.activeIdentityId)return json(res,400,{error:'cannot_follow_self'}); if(req.method==='POST')await pool.query('INSERT IGNORE INTO proton_identity_follows (follower_identity_id,followed_identity_id,created_by_account_id) VALUES (?,?,?)',[current.activeIdentityId,followed,current.accountId]);else await pool.query('DELETE FROM proton_identity_follows WHERE follower_identity_id=? AND followed_identity_id=?',[current.activeIdentityId,followed]); return json(res,200,{ok:true,following:req.method==='POST'}); }
  if (req.method === 'GET' && url.pathname === '/api/notifications') { const [rows]=await pool.query('SELECT public_id AS publicId,notification_type AS type,title,message,route,read_at AS readAt,created_at AS createdAt FROM proton_notifications WHERE account_id=? ORDER BY created_at DESC LIMIT 50',[current.accountId]); return json(res,200,{notifications:rows}); }
  if (req.method === 'POST' && url.pathname === '/api/notifications/read-all') { await pool.query('UPDATE proton_notifications SET read_at=COALESCE(read_at,NOW()) WHERE account_id=?',[current.accountId]); return json(res,200,{ok:true}); }
  const notificationMatch=url.pathname.match(/^\/api\/notifications\/([^/]+)\/read$/);
  if (req.method === 'PATCH' && notificationMatch) { await pool.query('UPDATE proton_notifications SET read_at=COALESCE(read_at,NOW()) WHERE public_id=? AND account_id=?',[notificationMatch[1],current.accountId]); return json(res,200,{ok:true}); }

  const profileMatch=url.pathname.match(/^\/api\/profiles\/([^/]+)$/);
  if (req.method === 'GET' && profileMatch) { const [rows]=await pool.query(`SELECT i.public_id AS publicId,i.identity_type AS type,i.username,i.display_name AS displayName,COALESCE(p.slug,i.username) AS slug,p.headline,COALESCE(p.bio,i.bio) AS bio,p.mood,p.location_label AS location,p.visibility,COALESCE(p.avatar_url,i.avatar_url) AS avatarUrl,COALESCE(p.cover_url,i.cover_url) AS coverUrl,p.interests,p.theme_json AS theme,(SELECT COUNT(*) FROM proton_identity_follows f WHERE f.followed_identity_id=i.id) AS followers,(SELECT COUNT(*) FROM proton_identity_follows f WHERE f.follower_identity_id=i.id) AS following FROM proton_identities i LEFT JOIN proton_profiles p ON p.identity_id=i.id WHERE (p.slug=? OR i.username=?) AND i.identity_status='active' AND i.visibility='public' LIMIT 1`,[profileMatch[1],profileMatch[1]]); const profile=(rows as any[])[0]; return profile?json(res,200,{profile}):json(res,404,{error:'profile_not_found'}); }
  if (req.method === 'PUT' && url.pathname === '/api/profile') { const input=await body(req); const displayName=String(input.displayName??'').trim().slice(0,140), slug=String(input.slug??'').toLowerCase().replace(/[^a-z0-9_-]/g,'').slice(0,80); if(!displayName||!slug)return json(res,400,{error:'display_name_and_slug_required'}); const identity=await activeIdentity(current); if(!identity||!identity.canEditProfile)return json(res,403,{error:'identity_profile_read_only'}); const visibility=['public','friends','private'].includes(input.visibility)?input.visibility:'public'; await pool.query('UPDATE proton_identities SET display_name=?,avatar_url=?,cover_url=?,bio=?,visibility=? WHERE id=?',[displayName,String(input.avatarUrl??'').slice(0,1000)||null,String(input.coverUrl??'').slice(0,1000)||null,String(input.bio??'').slice(0,5000)||null,visibility==='friends'?'followers':visibility,identity.id]); const theme=JSON.stringify(input.theme??{}); await pool.query(`INSERT INTO proton_profiles (account_id,identity_id,slug,headline,bio,mood,location_label,visibility,avatar_url,cover_url,interests,theme_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE slug=VALUES(slug),headline=VALUES(headline),bio=VALUES(bio),mood=VALUES(mood),location_label=VALUES(location_label),visibility=VALUES(visibility),avatar_url=VALUES(avatar_url),cover_url=VALUES(cover_url),interests=VALUES(interests),theme_json=VALUES(theme_json)`,[current.accountId,identity.id,slug,String(input.headline??'').slice(0,160),String(input.bio??'').slice(0,5000),String(input.mood??'').slice(0,80),String(input.location??'').slice(0,120),visibility,String(input.avatarUrl??'').slice(0,1000),String(input.coverUrl??'').slice(0,1000),String(input.interests??'').slice(0,2000),theme]); return json(res,200,{ok:true,slug}); }

  const postMatch=url.pathname.match(/^\/api\/posts\/([^/]+)$/);
  if ((req.method === 'PATCH' || req.method === 'DELETE') && postMatch) { const [posts]=await pool.query('SELECT id FROM proton_posts WHERE public_id=? AND account_id=? AND deleted_at IS NULL',[postMatch[1],current.accountId]); const post=(posts as any[])[0]; if(!post)return json(res,404,{error:'post_not_found'}); if(req.method==='DELETE'){await pool.query('UPDATE proton_posts SET deleted_at=NOW() WHERE id=?',[post.id]);return json(res,200,{ok:true});} const input=await body(req); const text=String(input.body??'').trim(); if(!text||text.length>2000)return json(res,400,{error:'invalid_body'}); await pool.query('UPDATE proton_posts SET body=?,edited_at=NOW() WHERE id=?',[text,post.id]); return json(res,200,{ok:true}); }
  const bookmarkMatch=url.pathname.match(/^\/api\/posts\/([^/]+)\/bookmark$/);
  if ((req.method === 'POST' || req.method === 'DELETE') && bookmarkMatch) { const [posts]=await pool.query('SELECT id FROM proton_posts WHERE public_id=? AND deleted_at IS NULL',[bookmarkMatch[1]]); const post=Number((posts as any[])[0]?.id); if(!post)return json(res,404,{error:'post_not_found'}); if(req.method==='POST')await pool.query('INSERT IGNORE INTO proton_bookmarks (account_id,post_id) VALUES (?,?)',[current.accountId,post]); else await pool.query('DELETE FROM proton_bookmarks WHERE account_id=? AND post_id=?',[current.accountId,post]); return json(res,200,{ok:true,bookmarked:req.method==='POST'}); }

  if (req.method === 'GET' && url.pathname === '/api/communities') { const [rows]=await pool.query(`SELECT c.public_id AS publicId,c.slug,c.name,c.description,c.visibility,COUNT(m.account_id) AS members,MAX(m.account_id=?) AS joined FROM proton_communities c LEFT JOIN proton_community_members m ON m.community_id=c.id AND m.membership_status='active' WHERE c.visibility='public' OR m.account_id=? GROUP BY c.id ORDER BY members DESC,c.created_at DESC`,[current.accountId,current.accountId]); return json(res,200,{communities:rows}); }
  if (req.method === 'POST' && url.pathname === '/api/communities') { const input=await body(req),name=String(input.name??'').trim().slice(0,140),slug=String(input.slug??'').toLowerCase().replace(/[^a-z0-9_-]/g,'').slice(0,100); if(!name||!slug)return json(res,400,{error:'name_and_slug_required'}); const id=publicId(); const [result]=await pool.query('INSERT INTO proton_communities (public_id,slug,name,description,owner_account_id,visibility,rules_text) VALUES (?,?,?,?,?,?,?)',[id,slug,name,String(input.description??'').slice(0,5000),current.accountId,['public','private','invite'].includes(input.visibility)?input.visibility:'public',String(input.rules??'').slice(0,10000)]); await pool.query('INSERT INTO proton_community_members (community_id,account_id,member_role) VALUES (?,? ,"owner")',[(result as any).insertId,current.accountId]); return json(res,201,{publicId:id,slug}); }
  const communityJoin=url.pathname.match(/^\/api\/communities\/([^/]+)\/membership$/);
  if ((req.method==='POST'||req.method==='DELETE')&&communityJoin) { const [rows]=await pool.query('SELECT id,visibility FROM proton_communities WHERE public_id=?',[communityJoin[1]]); const community=(rows as any[])[0]; if(!community)return json(res,404,{error:'community_not_found'}); if(req.method==='DELETE')await pool.query('DELETE FROM proton_community_members WHERE community_id=? AND account_id=? AND member_role<>"owner"',[community.id,current.accountId]); else await pool.query('INSERT INTO proton_community_members (community_id,account_id,membership_status) VALUES (?,?,?) ON DUPLICATE KEY UPDATE membership_status=VALUES(membership_status)',[community.id,current.accountId,community.visibility==='public'?'active':'pending']); return json(res,200,{ok:true}); }

  if (req.method === 'GET' && url.pathname === '/api/conversations') { const [rows]=await pool.query(`SELECT c.public_id AS publicId,c.title,c.conversation_type AS type,MAX(m.created_at) AS lastMessageAt,MAX(m.body) AS preview FROM proton_conversations c JOIN proton_conversation_members cm ON cm.conversation_id=c.id LEFT JOIN proton_messages m ON m.conversation_id=c.id AND m.deleted_at IS NULL WHERE cm.account_id=? GROUP BY c.id ORDER BY lastMessageAt DESC`,[current.accountId]); return json(res,200,{conversations:rows}); }
  if (req.method === 'POST' && url.pathname === '/api/conversations') { const input=await body(req),members=Array.isArray(input.memberPublicIds)?input.memberPublicIds.slice(0,25):[]; const id=publicId(); const [result]=await pool.query('INSERT INTO proton_conversations (public_id,conversation_type,title,created_by_account_id) VALUES (?,?,?,?)',[id,members.length>1?'group':'direct',String(input.title??'').slice(0,140)||null,current.accountId]); const conversationId=(result as any).insertId; await pool.query('INSERT INTO proton_conversation_members (conversation_id,account_id) VALUES (?,?)',[conversationId,current.accountId]); if(members.length){const [accounts]=await pool.query('SELECT id FROM proton_accounts WHERE public_id IN (?)',[members]); for(const account of accounts as any[])await pool.query('INSERT IGNORE INTO proton_conversation_members (conversation_id,account_id) VALUES (?,?)',[conversationId,account.id]);} return json(res,201,{publicId:id}); }
  const messagesMatch=url.pathname.match(/^\/api\/conversations\/([^/]+)\/messages$/);
  if (req.method === 'GET' && messagesMatch) { const [rows]=await pool.query(`SELECT m.public_id AS publicId,m.body,m.created_at AS createdAt,a.public_id AS senderPublicId,a.display_name AS displayName FROM proton_messages m JOIN proton_conversations c ON c.id=m.conversation_id JOIN proton_conversation_members cm ON cm.conversation_id=c.id AND cm.account_id=? JOIN proton_accounts a ON a.id=m.sender_account_id WHERE c.public_id=? AND m.deleted_at IS NULL ORDER BY m.created_at ASC LIMIT 200`,[current.accountId,messagesMatch[1]]); return json(res,200,{messages:rows}); }
  if (req.method === 'POST' && messagesMatch) { const input=await body(req),text=String(input.body??'').trim(); if(!text||text.length>4000)return json(res,400,{error:'invalid_body'}); const [rows]=await pool.query('SELECT c.id FROM proton_conversations c JOIN proton_conversation_members cm ON cm.conversation_id=c.id WHERE c.public_id=? AND cm.account_id=?',[messagesMatch[1],current.accountId]); const conversation=Number((rows as any[])[0]?.id); if(!conversation)return json(res,404,{error:'conversation_not_found'}); const id=publicId(); await pool.query('INSERT INTO proton_messages (public_id,conversation_id,sender_account_id,body) VALUES (?,?,?,?)',[id,conversation,current.accountId,text]); return json(res,201,{publicId:id}); }

  if (req.method === 'GET' && url.pathname === '/api/streams') { const [rows]=await pool.query(`SELECT s.public_id AS publicId,s.title,s.category,s.status,s.provider,s.playback_url AS playbackUrl,s.scheduled_at AS scheduledAt,a.display_name AS creatorName FROM proton_streams s JOIN proton_accounts a ON a.id=s.creator_account_id WHERE s.status IN ('scheduled','live') ORDER BY s.status='live' DESC,s.scheduled_at ASC LIMIT 50`); return json(res,200,{streams:rows}); }
  if (req.method === 'POST' && url.pathname === '/api/streams') { const input=await body(req),title=String(input.title??'').trim().slice(0,180); if(!title)return json(res,400,{error:'title_required'}); const id=publicId(); await pool.query('INSERT INTO proton_streams (public_id,creator_account_id,title,category,provider,playback_url,scheduled_at) VALUES (?,?,?,?,?,?,?)',[id,current.accountId,title,String(input.category??'General').slice(0,80),String(input.provider??'embed').slice(0,60),String(input.playbackUrl??'').slice(0,2000)||null,input.scheduledAt||null]); return json(res,201,{publicId:id}); }
  if (req.method === 'GET' && url.pathname === '/api/creator/summary') { const [rows]=await pool.query(`SELECT COALESCE(SUM(CASE WHEN settlement_status IN ('available','paid') THEN net_amount_minor ELSE 0 END),0) AS availableMinor,COALESCE(SUM(CASE WHEN settlement_status='pending' THEN net_amount_minor ELSE 0 END),0) AS pendingMinor,COUNT(*) AS transactions FROM proton_creator_ledger WHERE creator_account_id=?`,[current.accountId]); return json(res,200,{currency:'USD',...(rows as any[])[0]}); }
  if (req.method === 'POST' && url.pathname === '/api/reports') { const input=await body(req),targetType=String(input.targetType??'').slice(0,40),targetId=Number(input.targetId),reason=String(input.reason??'').slice(0,80); if(!targetType||!targetId||!reason)return json(res,400,{error:'invalid_report'}); const id=publicId(); await pool.query('INSERT INTO proton_reports (public_id,reporter_account_id,target_type,target_id,reason,details) VALUES (?,?,?,?,?,?)',[id,current.accountId,targetType,targetId,reason,String(input.details??'').slice(0,5000)]); return json(res,201,{publicId:id,status:'open'}); }
  if (req.method === 'GET' && url.pathname === '/api/integrations/cityos') { const [rows]=await pool.query('SELECT citizenid,display_character_publicly AS displayPublicly,linked_at AS linkedAt FROM proton_cityos_links WHERE account_id=?',[current.accountId]); return json(res,200,{links:rows}); }
  if (req.method === 'PATCH' && url.pathname === '/api/integrations/cityos') { const input=await body(req); await pool.query('UPDATE proton_cityos_links SET display_character_publicly=? WHERE account_id=? AND citizenid=?',[Boolean(input.displayPublicly),current.accountId,String(input.citizenId??'')]); return json(res,200,{ok:true}); }
  return json(res,404,{error:'not_found'});
}

createServer((req,res)=>{route(req,res).catch(err=>{console.error(err);json(res,500,{error:'internal_error'});});}).listen(port,()=>console.log(`[protonspace-api] listening on ${port}`));

// Called by the thin FiveM bridge after CityOS has verified a character. Never expose this endpoint publicly.
export function issueCityOSTicket(accountId:number,identityId:number,citizenId:string) { const ticket=randomUUID(); tickets.set(ticket,{accountId,identityId,citizenId,expiresAt:Date.now()+45000,used:false}); return ticket; }
